name: smart_arg_fork
description: A smart command line argument parser for Dart that provides
  argument validation, static type checking, command execution, beautiful
  help generation and more.
version: 4.0.0
homepage: https://github.com/axrs/smart_arg/tree/master-forked

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
  build_runner: ^2.1.4
  build_test: ^2.1.4

dependencies:
  path: ^1.8.0
  reflectable: ^3.0.4
  collection: ^1.15.0
  recase: ^4.0.0
